---
title: "TMSstroke_RMT-ARAT"
author: "Alica Rogojin"
output: html_document
date: "2023-02-24"
---

## Load the required libraries
```{r}
library(readr)
library(rmcorr) 
library(ggplot2) 
library(cowplot) 
library(RColorBrewer) 
library(rmcorr)
library(dplyr)
library(ggrepel)
```

## Load the data
```{r}
setwd("/Users/connectome/Documents/Postdoc/Baycrest/TMS_stroke/repositories")

dataRMT.ARAT <- read_csv("data/TMSstroke_RMT-ARAT_rmcorr.csv") #read in the raw data files

dataRMT.ARAT$sex <- factor(dataRMT.ARAT$sex,
                          level=c(0,1),
                          labels=c("male", "female")
                     ) 

head(dataRMT.ARAT, 9) #print the first 9 rows
```

## Get sample size
```{r}
n <- length(unique(dataRMT.ARAT$subID))
```

## Calculate rmcorr using selected columns
```{r}
rmc <- rmcorr(participant = subID,
                 measure1 = ARAT,
                 measure2 = unaffected_70,
                 dataset = dataRMT.ARAT,
                 CI.level = 0.95,
                 CIs = "analytic",
                 nreps = 100,
                 bstrap.out = FALSE)
rmc
```

## And plot the data
```{r}
plotData <- dataRMT.ARAT
plotData <- na.omit(select(plotData, all_of(c("subID", "ARAT", "unaffected_70", "timepoint")))) 
p.RMT.ARAT <- ggplot(plotData, aes(x = ARAT, y = unaffected_70, label = timepoint, 
                                   group = factor(subID), color = factor(subID))) +
  geom_text_repel(size = 3, direction = "both", hjust = "left") +
  geom_point(aes(colour = factor(subID))) +
  geom_line(aes(y = rmc$model$fitted.values), linetype = 1, alpha = 0.4) +
#  ggtitle("Main Plot Title") +
  ylab("Unaffected hemisphere RMT") +
  xlab("ARAT score") +
  theme_cowplot() +
  scale_shape_identity() +
  theme(legend.position = "none",
             plot.title = element_text(size = 20, hjust = 0.5),
             axis.title = element_text(size = 15),
             axis.text = element_text(size = 15),
             axis.text.x = element_text(angle = 0, hjust = 0, vjust = 0)) +
  scale_colour_manual(values = colorRampPalette(brewer.pal(12, "Paired"))(n))
p.RMT.ARAT

ggsave("p_RMTARAT.tiff", 
       plot = p.RMT.ARAT,
       width = 7,
       height = 7
)
```

## And plot the data --> CIHR grant
```{r}
plotDataCIHR <- dataRMT.ARAT
plotDataCIHR <- na.omit(select(plotDataCIHR, all_of(c("subID", "ARAT", "unaffected_70", "timepoint")))) 
p.RMT.ARAT.CIHR <- ggplot(plotDataCIHR, aes(x = ARAT, y = unaffected_70, #label = timepoint, 
                                   group = factor(subID), color = factor(subID))) +
#  geom_text_repel(size = 1, direction = "both", hjust = "left") +
  geom_point(aes(colour = factor(subID)), size = 1) +
  geom_line(aes(y = rmc$model$fitted.values), linetype = 1, alpha = 0.4) +
#  ggtitle("Main Plot Title") +
  ylab("Unaffected hemisphere RMT") +
  xlab("ARAT score") +
  theme_cowplot() +
  scale_shape_identity() +
  theme(legend.position = "none",
             plot.title = element_text(size = 5, hjust = 0.5),
             axis.title = element_text(size = 7),
             axis.text = element_text(size = 7),
             axis.text.x = element_text(angle = 0, hjust = 0, vjust = 0)) +
  scale_colour_manual(values = colorRampPalette(brewer.pal(12, "Paired"))(n))
p.RMT.ARAT.CIHR

ggsave("p_RMTARAT_CIHR.tiff", 
       plot = p.RMT.ARAT.CIHR,
       width = 2,
       height = 2
)
```



## Older code: Doing a pre/post correlation between ARAT and RMT difference scores
```{r}
# Calculate the difference scores (RMT post - pre) and (ARAT post - pre) and correlate those
# Could also normalize them to a percent change, i.e.,
# post - pre
# ----------- x 100
#    pre 

dataRMT.ARAT.old <- read_csv("data/TMSstroke_RMT-ARAT.csv") #read in the raw data files

dataRMT.ARAT.old$sex <- factor(dataRMT.ARAT.old$sex,
                          level=c(0,1),
                          labels=c("male", "female")
                     ) 

head(dataRMT.ARAT.old, 9) #print the first 9 rows
```

## Pre-checks of data before correlation analysis
```{r}
# Test for normality, if p > 0.05 can assume normality
shapiro.test(dataRMT.ARAT$ARAT_pre)$p # => p = 0.03604
shapiro.test(dataRMT.ARAT$ARAT_post)$p # => p = 0.05325
shapiro.test(dataRMT.ARAT$ARAT_diff_score)$p # => p = 0.5083
shapiro.test(dataRMT.ARAT$ARAT_diff_norm)$p # => p = 0.8189
shapiro.test(dataRMT.ARAT$affected_RMT_diff)$p # => p = 0.8899
shapiro.test(dataRMT.ARAT$affected_RMT_norm)$p # => p = 0.8121
shapiro.test(dataRMT.ARAT$unaffected_RMT_diff)$p # => p = 0.9979
shapiro.test(dataRMT.ARAT$unaffected_RMT_norm)$p # => p = 0.387

# Visual inspection of the data normality using Q-Q plots (quantile-quantile plots). Q-Q plot draws the correlation between a given sample and the normal distribution. If linear, conclude that both populations may come from normal distributions.
ggqqplot(dataRMT.ARAT$ARAT_diff_score, ylab = "ARAT_diff_score") # => linear
ggqqplot(dataRMT.ARAT$ARAT_diff_norm, ylab = "ARAT_diff_norm") # => linear
ggqqplot(dataRMT.ARAT$affected_RMT_diff, ylab = "affected_RMT_diff") # => linear
ggqqplot(dataRMT.ARAT$affected_RMT_norm, ylab = "affected_RMT_norm") # => linear
ggqqplot(dataRMT.ARAT$unaffected_RMT_diff, ylab = "unaffected_RMT_diff") # => linear
ggqqplot(dataRMT.ARAT$unaffected_RMT_norm, ylab = "unaffected_RMT_norm") # => linear
```

## Correlation analysis between ARAT and RMT (focusing on 70mm RMT)
```{r}
# ARAT and affected 70mm RMT
cor.affect.diffscore <- cor.test(dataRMT.ARAT$ARAT_diff_score, dataRMT.ARAT$affected_RMT_diff, 
         method = "pearson") # using just difference scores
cor.affect.normscore <- cor.test(dataRMT.ARAT$ARAT_diff_norm, dataRMT.ARAT$affected_RMT_norm, 
         method = "pearson") # using normalized difference scores

# ARAT and unaffected 70mm RMT
cor.unaffect.diffscore <- cor.test(dataRMT.ARAT$ARAT_diff_score, dataRMT.ARAT$unaffected_RMT_diff, 
         method = "pearson") # using just difference scores
cor.unaffect.normscore <- cor.test(dataRMT.ARAT$ARAT_diff_norm, dataRMT.ARAT$unaffected_RMT_norm, 
         method = "pearson") # using normalized difference scores

# extract the p-values and correlation coefficients (estimate)
cor.affect.diffscore$p.value
cor.affect.diffscore$estimate
cor.affect.normscore$p.value
cor.affect.normscore$estimate
cor.unaffect.diffscore$p.value
cor.unaffect.diffscore$estimate
cor.unaffect.normscore$p.value
cor.unaffect.normscore$estimate

# plot relationship
library(ggstatsplot)
p.affect.diffscore <- ggscatterstats(data = dataRMT.ARAT, x = ARAT_diff_score, y = affected_RMT_diff)
p.affect.diffscore
p.affect.normscore <- ggscatterstats(data = dataRMT.ARAT, x = ARAT_diff_norm, y = affected_RMT_norm)
p.affect.normscore
p.unaffect.diffscore <- ggscatterstats(data = dataRMT.ARAT, x = ARAT_diff_score, y = unaffected_RMT_diff)
p.unaffect.diffscore
p.unaffect.normscore <- ggscatterstats(data = dataRMT.ARAT, x = ARAT_diff_norm, y = unaffected_RMT_norm)
p.unaffect.normscore
```

